version: "3.5"
services:
  traefik:
    image: traefik:latest
    command:
      - "--api.insecure=true"
      - "--providers.docker=false"
      - "--providers.file.directory=/etc/traefik/dynamic_conf"
      - "--accesslog=true"
      - "--accesslog.fields.headers.defaultmode=keep"
      - "--accesslog.fields.headers.names.User-Agent=drop"
      - "--accesslog.fields.headers.names.Content-Type=drop"
      - "--entryPoints.web.address=:80"

    ports:
      - "8000:80"
      - "8181:8080" # The Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/dynamic_conf:/etc/traefik/dynamic_conf"
      - "./traefik/logs:/logs"
    networks:
      - traefik-ingress
      - faktenforum
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres-db:
    build:
      context: ./database
      dockerfile: Dockerfile.db-postgres
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}

    networks:
      - faktenforum

  graphql-engine:
    image: hasura/graphql-engine:v2.40.0-ce
    ports:
      - "8080:8080"
    restart: always
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-db:${POSTGRES_PORT}/hasura
      PGDATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-db:${POSTGRES_PORT}/faktenforum
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_READ_ONLY_MODE: "false"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_ADMIN_SECRET}
      HASURA_GRAPHQL_METADATA_DEFAULTS: '{"backend_configs":{"dataconnector":{"athena":{"uri":"http://data-connector-agent:8081/api/v1/athena"},"mariadb":{"uri":"http://data-connector-agent:8081/api/v1/mariadb"},"mysql8":{"uri":"http://data-connector-agent:8081/api/v1/mysql"},"oracle":{"uri":"http://data-connector-agent:8081/api/v1/oracle"},"snowflake":{"uri":"http://data-connector-agent:8081/api/v1/snowflake"}}}}'
      HASURA_GRAPHQL_AUTH_HOOK: ${HASURA_WEBHOOKS_BASE_URL}/session
      HASURA_WEBHOOKS_BASE_URL: ${HASURA_WEBHOOKS_BASE_URL}
      HASURA_WEBHOOKS_API_KEY: ${HASURA_API_KEY}
      HASURA_GRAPHQL_AUTH_HOOK_SEND_REQUEST_BODY: ${HASURA_GRAPHQL_AUTH_HOOK_SEND_REQUEST_BODY}
      HASURA_GRAPHQL_EXPERIMENTAL_FEATURES: "naming_convention"
      HASURA_GRAPHQL_DEFAULT_NAMING_CONVENTION: "graphql-default"
    # depends_on:
    #   data-connector-agent:
    #     condition: service_healthy
    networks:
      - faktenforum
      - traefik-ingress
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db-migrate:
    build:
      context: ./hasura
      dockerfile: Dockerfile.hasura-migrate
    depends_on:
      - postgres-db
      - graphql-engine
    environment:
      HASURA_ENDPOINT: "http://graphql-engine:8080"
      HASURA_ADMIN_SECRET: ${HASURA_ADMIN_SECRET}
      APPLY_METADATA: "true"
      APPLY_MIGRATIONS: "true"
      APPLY_SEEDS: "true"

    # import current files as volume so a rebuild is no required on database/metada changes
    volumes:
      - ./hasura:/app
    networks:
      - faktenforum

  minio:
    image: minio/minio:latest
    ports:
      - "${MINIO_API_PORT}:${MINIO_API_PORT}"
      - "${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}"
    environment:
      MINIO_SERVER_PORT: ${MINIO_API_PORT}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}"
    networks:
      - faktenforum
  # minio-client inits minio with a service account and a bucket
  minio-client:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      echo 'Waiting for MinIO to be ready...' &&
      sleep 5 &&
      mc alias set myminio http://minio:${MINIO_API_PORT} ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} &&
      mc admin user svcacct add  myminio ${MINIO_ROOT_USER} --access-key ${MINIO_ACCESS_KEY} --secret-key ${MINIO_SECRET_KEY} &&
      mc mb myminio/${MINIO_BUCKET_NAME} &&
      echo 'Service account and bucket created in MinIO'"
    networks:
      - faktenforum

  kratos-migrate:
    image: oryd/kratos:v1.3
    depends_on:
      - postgres-db
    environment:
      DSN: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-db:${POSTGRES_PORT}/kratos?sslmode=disable&max_conns=20&max_idle_conns=4

    volumes:
      - type: bind
        source: ./kratos/
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - faktenforum
      - traefik-ingress
  kratos:
    image: oryd/kratos:v1.3
    depends_on:
      - kratos-migrate
    environment:
      DSN: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-db:${POSTGRES_PORT}/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
      SELFSERVICE_FLOWS_REGISTRATION_AFTER_PASSWORD_HOOKS_0_CONFIG_AUTH_CONFIG_VALUE: ${KRATOS_API_KEY}
      SELFSERVICE_FLOWS_REGISTRATION_AFTER_PASSWORD_HOOKS_1_CONFIG_AUTH_CONFIG_VALUE: ${KRATOS_API_KEY}
      SECRETS_COOKIE: ${KRATOS_SECRETS_COOKIE}
      SECRETS_CIPHER: ${KRATOS_SECRETS_CIPHER}

    volumes:
      - type: bind
        source: ./kratos/
        target: /etc/config/kratos
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    ports:
      - "4433:4433" # public
      - "4434:4434" # admin
    restart: on-failure
    networks:
      - faktenforum
      - traefik-ingress
    extra_hosts:
      - "host.docker.internal:host-gateway"
  hydra-migrate:
    image: oryd/hydra:v2.2
    depends_on:
      - postgres-db
    environment:
      - DSN=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-db:${POSTGRES_PORT}/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
    command: migrate sql -e --yes
    restart: on-failure
    networks:
      - faktenforum
      - traefik-ingress
    extra_hosts:
      - "host.docker.internal:host-gateway"
  hydra:
    image: oryd/hydra:v2.2
    depends_on:
      - hydra-migrate
    ports:
      - "4444:4444" # Public port
      - "4445:4445" # Admin port
      - "5555:5555" # Port for hydra token user
    command: serve all --dev
    restart: on-failure # TODO figure out why we need this (incorporate health check into hydra migrate command?)
    environment:
      - LOG_LEAK_SENSITIVE_VALUES=true
      - URLS_SELF_ISSUER=http://app.localhost:8000
      - URLS_SELF_PUBLIC=http://app.localhost:8000
      - URLS_CONSENT=http://app.localhost:8000/api/v1/hydra-consent
      - URLS_LOGIN=http://app.localhost:8000/login
      - URLS_LOGOUT=http://pp.localhost:8000/logout
      - SECRETS_SYSTEM=youReallyNeedToChangeThis
      - OIDC_SUBJECT_IDENTIFIERS_SUPPORTED_TYPES=public,pairwise
      - OIDC_SUBJECT_IDENTIFIERS_PAIRWISE_SALT=youReallyNeedToChangeThis
      - DSN=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-db:${POSTGRES_PORT}/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
    networks:
      - faktenforum
      - traefik-ingress
    extra_hosts:
      - "host.docker.internal:host-gateway"

  hydra-consent:
    image: ghcr.io/lus/hydra-consent:latest
    restart: unless-stopped
    ports:
      - 4080:8080
    environment:
      #ENVIRONMENT: prod
      LOG_LEVEL: info
      LISTEN_ADDRESS: :8080
      HYDRA_ADMIN_API: http://hydra:4445
      # This field is optional. Only specify it if you want to enable the native Kratos trait propagation.
      KRATOS_ADMIN_API: http://kratos:4434
  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - "4436:4436"
      - "4437:4437"
    networks:
      - faktenforum
      - traefik-ingress
  matrix-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: synapse
      POSTGRES_USER: synapse_user
      POSTGRES_PASSWORD: synapse_password
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --lc-collate=C --lc-ctype=C

    volumes:
      - matrix_db_data:/var/lib/postgresql/data
    networks:
      - faktenforum

  matrix-server:
    image: docker.io/matrixdotorg/synapse:latest
    ports:
      - "8008:8008" # HTTP
      - "8448:8448" # Federation
    environment:
      SYNAPSE_ADMIN_USER: "@system:chat.localhost"
      SYNAPSE_ADMIN_PASSWORD: "abcd1234!D"
      SYNAPSE_CONFIG_PATH: /config/homeserver.yaml
      SYNAPSE_SERVER_NAME: "matrix.localhost"
      SYNAPSE_REPORT_STATS: "no"
      POSTGRES_DB: synapse
      POSTGRES_USER: synapse_user
      POSTGRES_PASSWORD: synapse_password
      POSTGRES_HOST: matrix-db
      UID: 0
      GID: 0
    restart: unless-stopped
    user: "0:0"
    volumes:
      - matrix_data:/data
      - ./matrix:/config/
    networks:
      - faktenforum
      - traefik-ingress
    depends_on:
      - matrix-db

  synapse-admin:
    image: awesometechnologies/synapse-admin:latest
    ports:
      - "8082:80"
    environment:
      SYNAPSE_ADMIN_URL: "http://matrix-server:8008"
    networks:
      - faktenforum
      - traefik-ingress
    depends_on:
      - matrix-server

volumes:
  db_data:
  minio_data:
  mailhog-data:
  mongodb_data:
  matrix_db_data:
  matrix_data:

networks:
  faktenforum:
    driver: bridge
  traefik-ingress:
    driver: bridge
