mutation insertFileAndUpdateSourceFile(
  $fileId: uuid!
  $eTag: String!
  $mimeType: String!
  $name: String!
  $size: Int!
  $entryId: uuid!
) {
  insertFileOne(object: { id: $fileId, eTag: $eTag, mimeType: $mimeType, name: $name, size: $size }) {
    id
  }
  updateSourceByPk(pkColumns: { id: $entryId }, _set: { fileId: $fileId }) {
    id
  }
}
