FROM alpine:latest

# Install bash and openss l
RUN apk add --no-cache bash openssl curl

# Set bash as the default shell
RUN curl -fsSL "https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64" -o /usr/bin/yq && chmod +x /usr/bin/yq

COPY ./homeserver.yaml.tmpl /conf/
COPY ./chat.faktenforum.log.config /conf/
COPY ./generate.sh /

RUN chmod +x /generate.sh
ENTRYPOINT ["/generate.sh"]