http:
  routers:
    backend:
      entryPoints:
        - web
      rule: host(`app.fafo.localhost`) && PathPrefix(`/api`)
      service: backend
  services:
    backend:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:8083
