http:
  routers:
    app:
      entryPoints:
        - web
      rule: host(`app.fafo.localhost`)
      service: app

  services:
    app:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:4000
