http:
  routers:
    traefik:
      entryPoints:
        - web
      rule: host(`traefik.localhost`)
      service: traefik

  services:
    traefik:
      loadBalancer:
        servers:
          - url: http://traefik:8080
