mutation anonymizeUserProfile($id: uuid!, $username: String!) {
  updateUserByPk(
    pkColumns: { id: $id }
    _set: {
      username: $username
      bio: null
      email: $username
      firstName: null
      lastName: null
      mobileNumber: null
      profileImage: $username
      pronouns: null
    }
  ) {
    id
  }
}
