sequenceDiagram
    participant User as Submitter
    participant CallerAPI as Faktenforum
    participant ProcessorAPI as DeepFake Detector
    User->>CallerAPI: Submit a claim
    activate CallerAPI
    CallerAPI->>ProcessorAPI: Send claim 
    activate ProcessorAPI
    ProcessorAPI->>CallerAPI: Send process id
    deactivate CallerAPI
    ProcessorAPI->>CallerAPI: Send process results
    activate CallerAPI
    deactivate ProcessorAPI
    CallerAPI->>User: Push notification / Frontend update
    activate User
    deactivate CallerAPI
    User->>CallerAPI: Rate process results 
    deactivate User
    CallerAPI->>ProcessorAPI: Send user process rating