ALTER TABLE "claim_category" ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE "claim" ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE "origin" ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE "fact" ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE "source" ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;
-- history tables
ALTER TABLE "claim_history" ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE "user_history" ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE "file_history" ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE "source_history" ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE "fact_history" ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE "origin_history" ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;

