ALTER TABLE "claim" ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE "origin" ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE "fact" ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE "source" ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;


