name: Build and Push DEV Docker Images
on:
  push:
    branches: [main, production, 16-publish-images-to-ghcr]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Generate a token for the GitHub App
      # Set tags for the main branch
      - name: Set Production Tags
        if: github.ref == 'refs/heads/production'
        run: |
          echo "VERSION=$(cat package.json | jq -r .version)" >> $GITHUB_ENV
          echo "TAGS=ghcr.io/${{ github.repository_owner }}/faktenforum-api:$VERSION,ghcr.io/${{ github.repository_owner }}/faktenforum-api:latest" >> $GITHUB_ENV

      # Set tag for development branches
      - name: Set Dev Tag
        if: github.ref != 'refs/heads/production'
        run: echo "TAGS=ghcr.io/${{ github.repository_owner }}/faktenforum-api:latest-dev" >> $GITHUB_ENV

      # Login into ghcr.io as action
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # build & publish  image  for arm64 and amd64
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64, linux/arm64
          tags: ${{ env.TAGS }}
