name: FF-API | Deploy

on:
  workflow_run:
    workflows: ["FF-API | Build & Push Docker Images"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DEV Environment
        if: github.ref != 'refs/heads/production'
        uses: jonasschatz/portami@main
        with:
          endpoint: ${{vars.DEV_PORTAINER_URL}}
          access_token: ${{ secrets.DEV_PORTAINER_ACCESSTOKEN }}
          stack_name: "faktenforum"
          prune: true
          pull: true

      - name: Deploy to Production Environment
        if: github.ref == 'refs/heads/production'
        uses: jonasschatz/portami@main
        with:
          endpoint: ${{vars.PORTAINER_URL}}
          access_token: ${{ secrets.PORTAINER_ACCESSTOKEN }}
          stack_name: "faktenforum"
          prune: true
          pull: true
