name: FF-API | Deploy

on:
  workflow_run:
    workflows: ["FF-API | Build and Push Docker Images"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: jonasschatz/portami@main
        with:
          endpoint: ${{vars.DEV_PORTAINER_URL}}
          access_token: ${{ secrets.DEV_PORTAINER_ACCESSTOKEN }}
          stack_name: "faktenforum"
          prune: true
          pull: true
