name: Build and Push DEV Docker Images
on:
  push:
    branches: [16-publish-images-to-ghcr]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Generate a token for the GitHub App 
      - name: Extract Version from package.json
        run: echo "VERSION=$(cat package.json | jq -r .version)" >> $GITHUB_ENV
        env:
          PACKAGE_JSON_PATH: './package.json'

      # Login into ghcr.io as action
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # publish the image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/faktenforum/faktenforum-api:latest-dev
